global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: whatsapp-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:4000"]

  - job_name: whatsapp-worker
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["worker"]
        type: A
        port: 9464
        refresh_interval: 15s
