import type { Locale } from "@/lib/i18n";

const en = {
  createTitle: "Create contact",
  createDescription: "Phone numbers are immutable identities. New manual contacts start without marketing consent.",
  phoneE164: "Phone (E.164)",
  displayName: "Display name",
  tags: "Tags",
  note: "Note",
  customFields: "Custom fields",
  keyValueHint: "one key=value per line",
  createContact: "Create contact",
  selected: "{count} selected",
  addTag: "Add tag",
  removeTag: "Remove tag",
  suppressionReasonOptional: "Suppression reason (optional)",
  tag: "Tag",
  applyBulkAction: "Apply bulk action",
  reviewDuplicates: "Review duplicates",
  select: "Select",
  contact: "Contact",
  consent: "Consent",
  fields: "Fields",
  notes: "Notes",
  actions: "Actions",
  edit: "Edit",
  reviewResubscribe: "Review resubscribe",
  noContactsFilters: "No contacts match these filters.",
  loadMore: "Load more",
  editContact: "Edit contact",
  immutablePhone: "Phone cannot be edited; use merge/deduplication for identity consolidation.",
  newNote: "New note",
  recentNotes: "Recent notes",
  saveChanges: "Save changes",
  duplicateCandidates: "Duplicate candidates",
  duplicateDescription: "Candidates are grouped only by identical normalized display name. Choose the target explicitly before merging; phone consent and suppression are never copied between numbers.",
  mergeTarget: "Merge target",
  keep: "Keep {phone}",
  mergeOthers: "Merge others into target",
  activityTitle: "Contact activity",
  activityDescription: "Manual create/edit, bulk actions, imports, and merges are recorded separately from consent history.",
  contactFallback: "Contact",
  loadFailed: "Could not load contacts",
  createFailed: "Could not create contact",
  created: "Contact created. Consent remains off until it is recorded through the consent flow.",
  updateFailed: "Could not update contact",
  updated: "Contact updated and recorded in activity history.",
  suppressConfirm: "Suppress this phone number? Pending/queued campaign recipients for it will be skipped.",
  manualSuppressionReason: "Manually suppressed from Contacts",
  suppressedMessage: "Contact suppressed.",
  selectOne: "Select at least one contact first.",
  bulkSuppressConfirm: "Suppress {count} selected contacts?",
  bulkSuppressionReason: "Bulk suppression from Contacts",
  bulkFailed: "Bulk action failed",
  bulkCompleted: "Bulk action completed for {count} contacts.",
  duplicateScanFailed: "Could not scan duplicate candidates",
  noDuplicates: "No duplicate display-name groups found.",
  mergeConfirm: "Merge {count} contact(s) into the selected target? Consent and suppression remain attached to each phone number.",
  duplicateReviewReason: "Duplicate display-name review",
  mergeFailed: "Merge failed",
  merged: "Contacts merged. The source records remain auditable but are excluded from future audiences.",
  invalidCustomField: "Invalid custom field: {line}. Use key=value.",
  invalidCustomFieldKey: "Invalid custom field key: {key}",
  importMappingTitle: "Import field mapping",
  importMappingDescription: "Map your CSV headers explicitly. Phone is required; custom fields use one field=CSV column mapping per line.",
  phoneColumn: "Phone column",
  displayNameColumn: "Display name column",
  doNotImport: "Do not import",
  mappingPlaceholder: "email=Email Address\ncompany=Company",
  emptyCsvHeader: "The CSV header row is empty.",
  csvHeaderReadFailed: "Could not read the CSV header row.",
  choosePhoneColumn: "Choose the CSV column that contains phone numbers.",
  invalidMapping: "Invalid custom field mapping: {line}. Use field=CSV column.",
  invalidMappingKey: "Invalid custom field key: {key}",
  columnNotFound: "CSV column not found: {column}",
  tooManyMappings: "Imports support at most 10 custom field mappings.",
  defaultOptInSource: "customer database consent",
} as const;

export type ContactManagementCopy = { [K in keyof typeof en]: string };

const ar: ContactManagementCopy = {
  createTitle: "إنشاء جهة اتصال",
  createDescription: "رقم الهاتف هو هوية ثابتة. تبدأ جهات الاتصال المنشأة يدوياً من دون موافقة تسويقية.",
  phoneE164: "الهاتف (E.164)",
  displayName: "اسم العرض",
  tags: "الوسوم",
  note: "ملاحظة",
  customFields: "الحقول المخصصة",
  keyValueHint: "سطر واحد لكل key=value",
  createContact: "إنشاء جهة اتصال",
  selected: "تم تحديد {count}",
  addTag: "إضافة وسم",
  removeTag: "إزالة وسم",
  suppressionReasonOptional: "سبب الحظر (اختياري)",
  tag: "وسم",
  applyBulkAction: "تطبيق الإجراء الجماعي",
  reviewDuplicates: "مراجعة التكرارات",
  select: "تحديد",
  contact: "جهة الاتصال",
  consent: "الموافقة",
  fields: "الحقول",
  notes: "الملاحظات",
  actions: "الإجراءات",
  edit: "تعديل",
  reviewResubscribe: "مراجعة إعادة الاشتراك",
  noContactsFilters: "لا توجد جهات اتصال تطابق هذه المرشحات.",
  loadMore: "تحميل المزيد",
  editContact: "تعديل جهة الاتصال",
  immutablePhone: "لا يمكن تعديل رقم الهاتف؛ استخدم الدمج/إزالة التكرار لتوحيد الهوية.",
  newNote: "ملاحظة جديدة",
  recentNotes: "الملاحظات الأخيرة",
  saveChanges: "حفظ التغييرات",
  duplicateCandidates: "مرشحو التكرار",
  duplicateDescription: "يتم تجميع المرشحين فقط عند تطابق اسم العرض بعد التطبيع. اختر الهدف صراحة قبل الدمج؛ لا يتم نسخ الموافقة أو الحظر بين أرقام الهاتف.",
  mergeTarget: "هدف الدمج",
  keep: "الاحتفاظ بـ {phone}",
  mergeOthers: "دمج البقية في الهدف",
  activityTitle: "نشاط جهة الاتصال",
  activityDescription: "يتم تسجيل الإنشاء والتعديل والإجراءات الجماعية والاستيراد والدمج بشكل منفصل عن سجل الموافقة.",
  contactFallback: "جهة اتصال",
  loadFailed: "تعذر تحميل جهات الاتصال",
  createFailed: "تعذر إنشاء جهة الاتصال",
  created: "تم إنشاء جهة الاتصال. تبقى الموافقة متوقفة حتى يتم تسجيلها عبر مسار الموافقة.",
  updateFailed: "تعذر تحديث جهة الاتصال",
  updated: "تم تحديث جهة الاتصال وتسجيل التغيير في سجل النشاط.",
  suppressConfirm: "هل تريد حظر رقم الهاتف هذا؟ سيتم تجاوز مستلمي الحملات المعلقين أو الموجودين في الطابور لهذا الرقم.",
  manualSuppressionReason: "حظر يدوي من صفحة جهات الاتصال",
  suppressedMessage: "تم حظر جهة الاتصال.",
  selectOne: "حدد جهة اتصال واحدة على الأقل أولاً.",
  bulkSuppressConfirm: "هل تريد حظر {count} من جهات الاتصال المحددة؟",
  bulkSuppressionReason: "حظر جماعي من صفحة جهات الاتصال",
  bulkFailed: "فشل الإجراء الجماعي",
  bulkCompleted: "اكتمل الإجراء الجماعي لـ {count} جهة اتصال.",
  duplicateScanFailed: "تعذر فحص مرشحي التكرار",
  noDuplicates: "لم يتم العثور على مجموعات مكررة لاسم العرض.",
  mergeConfirm: "هل تريد دمج {count} جهة اتصال في الهدف المحدد؟ تبقى الموافقة والحظر مرتبطين بكل رقم هاتف.",
  duplicateReviewReason: "مراجعة تكرار اسم العرض",
  mergeFailed: "فشل الدمج",
  merged: "تم دمج جهات الاتصال. تبقى السجلات المصدر قابلة للتدقيق لكنها مستبعدة من الجماهير المستقبلية.",
  invalidCustomField: "حقل مخصص غير صالح: {line}. استخدم key=value.",
  invalidCustomFieldKey: "مفتاح حقل مخصص غير صالح: {key}",
  importMappingTitle: "تعيين حقول الاستيراد",
  importMappingDescription: "عيّن عناوين CSV صراحة. الهاتف مطلوب، واستخدم تعيين field=CSV column واحداً في كل سطر للحقول المخصصة.",
  phoneColumn: "عمود الهاتف",
  displayNameColumn: "عمود اسم العرض",
  doNotImport: "عدم الاستيراد",
  mappingPlaceholder: "email=Email Address\ncompany=Company",
  emptyCsvHeader: "صف عناوين CSV فارغ.",
  csvHeaderReadFailed: "تعذر قراءة صف عناوين CSV.",
  choosePhoneColumn: "اختر عمود CSV الذي يحتوي على أرقام الهاتف.",
  invalidMapping: "تعيين حقل مخصص غير صالح: {line}. استخدم field=CSV column.",
  invalidMappingKey: "مفتاح حقل مخصص غير صالح: {key}",
  columnNotFound: "لم يتم العثور على عمود CSV: {column}",
  tooManyMappings: "يدعم الاستيراد 10 تعيينات للحقول المخصصة كحد أقصى.",
  defaultOptInSource: "موافقة قاعدة بيانات العملاء",
};

export function getContactManagementCopy(locale: Locale): ContactManagementCopy {
  return locale === "ar" ? ar : en;
}
