import type { Locale } from "@/lib/i18n";

const en = {
  pageTitle: "Set up your workspace",
  pageSubtitle: "Finish the essentials in your own order. Existing work is detected automatically, and you can leave and resume at any time.",
  yourSetup: "Your setup",
  setupProgress: "Setup progress",
  openGuide: "Open setup guide",
  resumeOnboarding: "Resume onboarding",
  skipOnboarding: "Skip onboarding",
  markComplete: "Mark onboarding complete",
  complete: "Completed",
  incomplete: "Incomplete",
  skipped: "Skipped",
  optional: "Optional",
  emailVerified: "Email verified",
  emailPending: "Verify your email address before relying on this workspace in production.",
  consentRequired: "Consent confirmation is required before onboarding can be skipped or marked complete.",
  consentLabel: "I confirm this workspace will only message contacts with valid WhatsApp opt-in and will honor opt-outs and suppressions.",
  confirmConsent: "Confirm consent requirements",
  skipStep: "Skip step",
  testModeTitle: "Send a safe onboarding test",
  testModeDescription: "This uses the real campaign engine with a frozen recipient snapshot. Choose a small opted-in audience before sending.",
  testModeLimit: "Onboarding test campaigns are limited to 5 eligible contacts.",
  testModeImmediate: "Onboarding tests send immediately and cannot be scheduled.",
  testModeAudienceTooLarge: "Choose an audience with 5 or fewer eligible contacts.",
  testModeSend: "Send onboarding test to {count} contacts",
  testModeSuccess: "Test accepted successfully. Return to onboarding to continue.",
  testModeFailure: "The test did not complete successfully. Review the campaign failure, fix the issue, and retry.",
  completedBanner: "Onboarding is complete. You can still use this guide whenever you want to review setup.",
  skippedBanner: "Onboarding is currently skipped. Resume it to continue tracking setup progress.",
  readOnly: "Only workspace owners and admins can change onboarding status or confirm consent.",
  steps: {
    workspace: { title: "Workspace details", description: "Review the organization name, timezone, default country, and preferred language.", cta: "Review workspace" },
    whatsapp: { title: "Connect WhatsApp Business", description: "Use the existing Meta Embedded Signup flow to connect a business and phone number.", cta: "Connect WhatsApp" },
    contacts: { title: "Import contacts", description: "Import opted-in contacts with the existing contact import flow.", cta: "Import contacts" },
    consent: { title: "Confirm consent requirements", description: "Acknowledge the workspace responsibility to use valid opt-in and honor suppression rules.", cta: "Review consent" },
    template: { title: "Sync or create a template", description: "An approved template is required before a campaign can send.", cta: "Manage templates" },
    audience: { title: "Create an audience", description: "Create a list or reusable segment for campaign targeting.", cta: "Build audience" },
    test: { title: "Send a test message", description: "Use the campaign engine with a small opted-in audience before the first production campaign.", cta: "Send test" },
    campaign: { title: "Launch the first campaign", description: "Create and launch a campaign once the connection, template, audience, and consent are ready.", cta: "Create campaign" },
  },
  dashboard: {
    workspaceCreated: "Workspace created",
    whatsappConnected: "WhatsApp connected",
    contactsImported: "Import contacts",
    templateReady: "Create template",
    audienceReady: "Create audience",
    firstCampaign: "Send first campaign",
  },
  empty: {
    contacts: { title: "No contacts yet", description: "Import opted-in contacts to start building lists and segments.", cta: "Import contacts", href: "/dashboard#contacts" },
    audiences: { title: "No audiences yet", description: "Import contacts, then create a list or segment for reusable targeting.", cta: "Open setup guide", href: "/onboarding" },
    templates: { title: "No templates yet", description: "Sync approved templates from Meta or create your first template using the template tools on this page.", cta: "Open setup guide", href: "/onboarding" },
    campaigns: { title: "No campaigns yet", description: "Complete the connection, template, consent, and audience steps before launching your first campaign.", cta: "Open setup guide", href: "/onboarding" },
  },
} as const;

const ar = {
  pageTitle: "إعداد مساحة العمل",
  pageSubtitle: "أكمل الخطوات الأساسية بالترتيب الذي يناسبك. يتم اكتشاف العمل الموجود تلقائياً ويمكنك المغادرة والعودة والمتابعة في أي وقت.",
  yourSetup: "إعدادك",
  setupProgress: "تقدم الإعداد",
  openGuide: "فتح دليل الإعداد",
  resumeOnboarding: "متابعة الإعداد",
  skipOnboarding: "تخطي الإعداد",
  markComplete: "اعتبار الإعداد مكتملاً",
  complete: "مكتمل",
  incomplete: "غير مكتمل",
  skipped: "تم التخطي",
  optional: "اختياري",
  emailVerified: "تم التحقق من البريد الإلكتروني",
  emailPending: "تحقق من بريدك الإلكتروني قبل الاعتماد على مساحة العمل هذه في بيئة الإنتاج.",
  consentRequired: "يجب تأكيد متطلبات الموافقة قبل تخطي الإعداد أو اعتباره مكتملاً.",
  consentLabel: "أؤكد أن مساحة العمل ستراسل فقط جهات اتصال لديها موافقة صالحة على واتساب وستحترم إلغاء الاشتراك وقوائم الحظر.",
  confirmConsent: "تأكيد متطلبات الموافقة",
  skipStep: "تخطي الخطوة",
  testModeTitle: "إرسال اختبار آمن للإعداد",
  testModeDescription: "يستخدم هذا محرك الحملات الحقيقي مع لقطة ثابتة للمستلمين. اختر جمهوراً صغيراً لديه موافقة قبل الإرسال.",
  testModeLimit: "حملات الاختبار أثناء الإعداد محدودة بخمس جهات اتصال مؤهلة.",
  testModeImmediate: "يتم إرسال اختبار الإعداد فوراً ولا يمكن جدولته.",
  testModeAudienceTooLarge: "اختر جمهوراً يحتوي على خمس جهات اتصال مؤهلة أو أقل.",
  testModeSend: "إرسال اختبار الإعداد إلى {count} جهات اتصال",
  testModeSuccess: "تم قبول الاختبار بنجاح. ارجع إلى الإعداد للمتابعة.",
  testModeFailure: "لم يكتمل الاختبار بنجاح. راجع فشل الحملة وأصلح المشكلة ثم أعد المحاولة.",
  completedBanner: "اكتمل الإعداد. يمكنك استخدام هذا الدليل في أي وقت لمراجعة الإعدادات.",
  skippedBanner: "تم تخطي الإعداد حالياً. استأنفه لمتابعة تقدم الإعداد.",
  readOnly: "يمكن لمالك مساحة العمل أو المسؤول فقط تغيير حالة الإعداد أو تأكيد الموافقة.",
  steps: {
    workspace: { title: "تفاصيل مساحة العمل", description: "راجع اسم المؤسسة والمنطقة الزمنية والدولة الافتراضية واللغة المفضلة.", cta: "مراجعة مساحة العمل" },
    whatsapp: { title: "ربط واتساب للأعمال", description: "استخدم تدفق Meta Embedded Signup الحالي لربط النشاط التجاري ورقم الهاتف.", cta: "ربط واتساب" },
    contacts: { title: "استيراد جهات الاتصال", description: "استورد جهات الاتصال التي وافقت على التواصل باستخدام تدفق الاستيراد الحالي.", cta: "استيراد جهات الاتصال" },
    consent: { title: "تأكيد متطلبات الموافقة", description: "أكد مسؤولية مساحة العمل عن استخدام موافقات صالحة واحترام قواعد الحظر وإلغاء الاشتراك.", cta: "مراجعة الموافقة" },
    template: { title: "مزامنة أو إنشاء قالب", description: "يلزم قالب معتمد قبل أن تتمكن الحملة من الإرسال.", cta: "إدارة القوالب" },
    audience: { title: "إنشاء جمهور", description: "أنشئ قائمة أو شريحة قابلة لإعادة الاستخدام لاستهداف الحملات.", cta: "إنشاء جمهور" },
    test: { title: "إرسال رسالة اختبار", description: "استخدم محرك الحملات مع جمهور صغير لديه موافقة قبل أول حملة فعلية.", cta: "إرسال اختبار" },
    campaign: { title: "إطلاق الحملة الأولى", description: "أنشئ حملة وأطلقها بعد تجهيز الاتصال والقالب والجمهور والموافقة.", cta: "إنشاء حملة" },
  },
  dashboard: {
    workspaceCreated: "تم إنشاء مساحة العمل",
    whatsappConnected: "تم ربط واتساب",
    contactsImported: "استيراد جهات الاتصال",
    templateReady: "إنشاء قالب",
    audienceReady: "إنشاء جمهور",
    firstCampaign: "إرسال الحملة الأولى",
  },
  empty: {
    contacts: { title: "لا توجد جهات اتصال بعد", description: "استورد جهات اتصال لديها موافقة للبدء بإنشاء القوائم والشرائح.", cta: "استيراد جهات الاتصال", href: "/dashboard#contacts" },
    audiences: { title: "لا توجد جماهير بعد", description: "استورد جهات الاتصال ثم أنشئ قائمة أو شريحة للاستهداف المتكرر.", cta: "فتح دليل الإعداد", href: "/onboarding" },
    templates: { title: "لا توجد قوالب بعد", description: "زامن القوالب المعتمدة من Meta أو أنشئ قالبك الأول باستخدام أدوات القوالب في هذه الصفحة.", cta: "فتح دليل الإعداد", href: "/onboarding" },
    campaigns: { title: "لا توجد حملات بعد", description: "أكمل الاتصال والقالب والموافقة والجمهور قبل إطلاق حملتك الأولى.", cta: "فتح دليل الإعداد", href: "/onboarding" },
  },
} as const;

export type OnboardingCopy = typeof en | typeof ar;

export function getOnboardingCopy(locale: Locale): OnboardingCopy {
  return locale === "ar" ? ar : en;
}
