export type ReportingLocale = "en" | "ar";

const en = {
  reports: "Reports & analytics",
  reportsSubtitle: "Organization-wide delivery, engagement, audience, template, and phone-number performance.",
  campaigns: "Campaign reports",
  campaignsSubtitle: "Compare campaign delivery, reads, failures, and opt-outs across the selected period.",
  templates: "Template reports",
  templatesSubtitle: "Understand which templates are used most and how their message delivery performs.",
  audiences: "Audience reports",
  audiencesSubtitle: "Compare lists and segments by campaign usage and recipient outcomes.",
  phoneNumbers: "Phone number reports",
  phoneNumbersSubtitle: "Review sending volume, quality, throughput, delivery, and failures by connected number.",
  overview: "Overview",
  filters: "Filters",
  dateRange: "Date range",
  today: "Today",
  last7: "Last 7 days",
  last30: "Last 30 days",
  custom: "Custom range",
  from: "From",
  to: "To",
  phoneNumber: "Phone number",
  campaign: "Campaign",
  template: "Template",
  allPhoneNumbers: "All phone numbers",
  allCampaigns: "All campaigns",
  allTemplates: "All templates",
  apply: "Apply filters",
  reset: "Reset",
  exportCsv: "Export CSV",
  totalCampaigns: "Total campaigns",
  recipients: "Recipients",
  submitted: "Messages submitted",
  accepted: "Accepted",
  sent: "Sent",
  delivered: "Delivered",
  read: "Read",
  failed: "Failed",
  skipped: "Skipped",
  optOuts: "Opt-outs",
  acceptanceRate: "Acceptance rate",
  deliveryRate: "Delivery rate",
  readRate: "Read rate",
  failureRate: "Failure rate",
  optOutRate: "Opt-out rate",
  messagesOverTime: "Messages over time",
  deliveryOverTime: "Delivery over time",
  readRateOverTime: "Read rate over time",
  failuresOverTime: "Failures over time",
  optOutsOverTime: "Opt-outs over time",
  campaignComparison: "Campaign comparison",
  campaignComparisonSubtitle: "Server-aggregated outcomes; only the current table page is sent to the browser.",
  audienceSize: "Audience size",
  deliveryPercent: "Delivery %",
  readPercent: "Read %",
  failurePercent: "Failure %",
  usage: "Template usage",
  language: "Language",
  listSegment: "List / segment",
  type: "Type",
  number: "Number",
  quality: "Quality",
  throughput: "Throughput",
  throughputUnit: "MPS",
  noData: "No reporting data for this selection.",
  noDataHelp: "Try a wider date range or remove one of the filters.",
  previous: "Previous",
  next: "Next",
  page: "Page",
  of: "of",
  loading: "Loading reports…",
  errorTitle: "Reports could not be loaded",
  errorHelp: "Retry the request. If the problem continues, review the application logs and database health.",
  retry: "Retry",
  sourceTruth: "Recipient rows are the source of truth; aggregates are calculated on the server.",
  timezone: "Workspace timezone",
};

const ar: typeof en = {
  reports: "التقارير والتحليلات",
  reportsSubtitle: "أداء التسليم والتفاعل والجمهور والقوالب وأرقام الهاتف على مستوى مساحة العمل.",
  campaigns: "تقارير الحملات",
  campaignsSubtitle: "قارن التسليم والقراءة والإخفاقات وإلغاء الاشتراك بين الحملات خلال الفترة المحددة.",
  templates: "تقارير القوالب",
  templatesSubtitle: "تعرّف على القوالب الأكثر استخداماً وكيفية أداء تسليم رسائلها.",
  audiences: "تقارير الجمهور",
  audiencesSubtitle: "قارن القوائم والشرائح حسب استخدام الحملات ونتائج المستلمين.",
  phoneNumbers: "تقارير أرقام الهاتف",
  phoneNumbersSubtitle: "راجع حجم الإرسال والجودة ومعدل النقل والتسليم والإخفاقات لكل رقم متصل.",
  overview: "نظرة عامة",
  filters: "عوامل التصفية",
  dateRange: "النطاق الزمني",
  today: "اليوم",
  last7: "آخر 7 أيام",
  last30: "آخر 30 يوماً",
  custom: "نطاق مخصص",
  from: "من",
  to: "إلى",
  phoneNumber: "رقم الهاتف",
  campaign: "الحملة",
  template: "القالب",
  allPhoneNumbers: "كل أرقام الهاتف",
  allCampaigns: "كل الحملات",
  allTemplates: "كل القوالب",
  apply: "تطبيق عوامل التصفية",
  reset: "إعادة الضبط",
  exportCsv: "تصدير CSV",
  totalCampaigns: "إجمالي الحملات",
  recipients: "المستلمون",
  submitted: "الرسائل المقدمة",
  accepted: "المقبولة",
  sent: "المرسلة",
  delivered: "تم التسليم",
  read: "تمت القراءة",
  failed: "فشلت",
  skipped: "تم تخطيها",
  optOuts: "إلغاء الاشتراك",
  acceptanceRate: "معدل القبول",
  deliveryRate: "معدل التسليم",
  readRate: "معدل القراءة",
  failureRate: "معدل الفشل",
  optOutRate: "معدل إلغاء الاشتراك",
  messagesOverTime: "الرسائل عبر الزمن",
  deliveryOverTime: "التسليم عبر الزمن",
  readRateOverTime: "معدل القراءة عبر الزمن",
  failuresOverTime: "الإخفاقات عبر الزمن",
  optOutsOverTime: "إلغاء الاشتراك عبر الزمن",
  campaignComparison: "مقارنة الحملات",
  campaignComparisonSubtitle: "يتم التجميع على الخادم، ولا تُرسل إلى المتصفح إلا صفحة الجدول الحالية.",
  audienceSize: "حجم الجمهور",
  deliveryPercent: "نسبة التسليم",
  readPercent: "نسبة القراءة",
  failurePercent: "نسبة الفشل",
  usage: "استخدام القالب",
  language: "اللغة",
  listSegment: "القائمة / الشريحة",
  type: "النوع",
  number: "الرقم",
  quality: "الجودة",
  throughput: "معدل النقل",
  throughputUnit: "رسالة/ث",
  noData: "لا توجد بيانات تقارير لهذا التحديد.",
  noDataHelp: "جرّب نطاقاً زمنياً أوسع أو أزل أحد عوامل التصفية.",
  previous: "السابق",
  next: "التالي",
  page: "الصفحة",
  of: "من",
  loading: "جارٍ تحميل التقارير…",
  errorTitle: "تعذر تحميل التقارير",
  errorHelp: "أعد المحاولة. إذا استمرت المشكلة، راجع سجلات التطبيق وصحة قاعدة البيانات.",
  retry: "إعادة المحاولة",
  sourceTruth: "صفوف المستلمين هي مصدر الحقيقة ويتم حساب التجميعات على الخادم.",
  timezone: "المنطقة الزمنية لمساحة العمل",
};

export function getReportingCopy(locale: ReportingLocale) {
  return locale === "ar" ? ar : en;
}
