"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/i18n-provider";

type ListOption = { id: string; name: string; memberCount: number };
type Filter = { field: "list"; operator: "in"; value: string } | { field: "display_name"; operator: "contains" | "starts_with" | "equals" | "is_empty"; value?: string } | { field: "phone_e164"; operator: "starts_with" | "ends_with" | "equals"; value: string };
type Preview = { count: number; sample: Array<{ id: string; displayName: string | null; phoneE164: string }> };
function defaultFilter(lists: ListOption[]): Filter { return lists[0] ? { field: "list", operator: "in", value: lists[0].id } : { field: "display_name", operator: "contains", value: "" }; }

export function AudienceManager({ lists }: { lists: ListOption[] }) {
  const router = useRouter(); const { messages, number, format } = useI18n();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [match, setMatch] = useState<"all" | "any">("all"); const [filters, setFilters] = useState<Filter[]>([defaultFilter(lists)]); const [preview, setPreview] = useState<Preview | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState<"preview" | "save" | null>(null);
  const valid = useMemo(() => filters.every((filter) => filter.field === "list" ? Boolean(filter.value) : filter.field === "display_name" && filter.operator === "is_empty" ? true : Boolean(filter.value?.trim())), [filters]);
  const setField = (index: number, field: Filter["field"]) => { setFilters((current) => current.map((filter, position) => position !== index ? filter : field === "list" ? { field: "list", operator: "in", value: lists[0]?.id ?? "" } : field === "display_name" ? { field: "display_name", operator: "contains", value: "" } : { field: "phone_e164", operator: "starts_with", value: "+" })); setPreview(null); };
  const updateFilter = (index: number, patch: Record<string, string>) => { setFilters((current) => current.map((filter, position) => position === index ? ({ ...filter, ...patch } as Filter) : filter)); setPreview(null); };
  const previewAudience = async (): Promise<Preview | null> => { if (!valid) return setMessage(messages.ui.completeFiltersPreview), null; setBusy("preview"); setMessage(null); try { const response = await fetch("/api/audiences/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ match, filters }) }); const result = (await response.json()) as Preview & { error?: string }; if (!response.ok) throw new Error(result.error ?? messages.ui.previewFailed); setPreview(result); return result; } catch (error) { setMessage(error instanceof Error ? error.message : messages.ui.previewFailed); return null; } finally { setBusy(null); } };
  const save = async () => { if (!name.trim()) return setMessage(messages.ui.segmentNeedsName); if (!valid) return setMessage(messages.ui.completeFiltersSave); setBusy("save"); setMessage(null); try { const response = await fetch("/api/audiences/segments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, definition: { match, filters } }) }); const result = (await response.json()) as { id?: string; error?: string }; if (!response.ok || !result.id) throw new Error(result.error ?? messages.ui.saveSegmentFailed); setMessage(messages.ui.segmentSaved); setName(""); setDescription(""); setPreview(null); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : messages.ui.saveSegmentFailed); } finally { setBusy(null); } };

  return <div style={{ display: "grid", gap: 16 }}>
    <div className="formGrid3"><label className="formLabel">{messages.ui.segmentName}<input maxLength={120} onChange={(event) => setName(event.target.value)} placeholder={messages.ui.segmentNamePlaceholder} value={name} /></label><label className="formLabel">{messages.ui.description} <span className="subtitle">({messages.common.optional})</span><input maxLength={500} onChange={(event) => setDescription(event.target.value)} placeholder={messages.ui.segmentDescriptionPlaceholder} value={description} /></label><label className="formLabel">{messages.ui.match}<select onChange={(event) => { setMatch(event.target.value as "all" | "any"); setPreview(null); }} value={match}><option value="all">{messages.ui.allFilters}</option><option value="any">{messages.ui.anyFilter}</option></select></label></div>
    <div style={{ display: "grid", gap: 10 }}>{filters.map((filter, index) => <div key={index} className="filterBuilderRow"><select onChange={(event) => setField(index, event.target.value as Filter["field"])} value={filter.field}><option value="list">{messages.ui.listMembership}</option><option value="display_name">{messages.ui.contactName}</option><option value="phone_e164">{messages.ui.phoneNumber}</option></select>{filter.field === "list" ? <select disabled value="in"><option value="in">{messages.ui.isInList}</option></select> : filter.field === "display_name" ? <select onChange={(event) => updateFilter(index, { operator: event.target.value })} value={filter.operator}><option value="contains">{messages.ui.contains}</option><option value="starts_with">{messages.ui.startsWith}</option><option value="equals">{messages.ui.equals}</option><option value="is_empty">{messages.ui.isEmpty}</option></select> : <select onChange={(event) => updateFilter(index, { operator: event.target.value })} value={filter.operator}><option value="starts_with">{messages.ui.startsWith}</option><option value="ends_with">{messages.ui.endsWith}</option><option value="equals">{messages.ui.equals}</option></select>}{filter.field === "list" ? <select onChange={(event) => updateFilter(index, { value: event.target.value })} value={filter.value}>{lists.length ? lists.map((list) => <option key={list.id} value={list.id}>{list.name} · {number(list.memberCount)}</option>) : <option value="">{messages.ui.noListsYet}</option>}</select> : filter.field === "display_name" && filter.operator === "is_empty" ? <span className="subtitle">{messages.ui.noValueRequired}</span> : <input onChange={(event) => updateFilter(index, { value: event.target.value })} placeholder={filter.field === "phone_e164" ? "+964" : messages.ui.value} value={filter.value ?? ""} />}<button className="secondary" disabled={filters.length === 1} onClick={() => { setFilters((current) => current.filter((_, position) => position !== index)); setPreview(null); }} type="button">{messages.ui.remove}</button></div>)}</div>
    <div className="actionRow"><button className="secondary" disabled={filters.length >= 20} onClick={() => setFilters((current) => [...current, defaultFilter(lists)])} type="button">{messages.ui.addFilter}</button><button className="secondary" disabled={busy !== null || !valid} onClick={() => void previewAudience()} type="button">{busy === "preview" ? messages.ui.previewing : messages.ui.previewAudience}</button><button className="primary" disabled={busy !== null || !valid || !name.trim()} onClick={() => void save()} type="button">{busy === "save" ? messages.common.saving : messages.ui.saveSegment}</button>{message ? <span className="subtitle">{message}</span> : null}</div>
    {preview ? <div className="numberRow" style={{ alignItems: "start" }}><div><strong>{format(messages.ui.eligibleContactsCount, { count: number(preview.count) })}</strong><p>{messages.ui.safetyBeforeCount}</p></div><div className="numberMeta">{preview.sample.slice(0, 5).map((contact) => <span key={contact.id}>{contact.displayName ?? messages.ui.unnamed} · <bdi>{contact.phoneE164}</bdi></span>)}</div></div> : null}
  </div>;
}
