"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/i18n-provider";
type Action = "pause" | "resume" | "cancel";

export function CampaignControls({ campaignId, initialStatus }: { campaignId: string; initialStatus: string }) {
  const router = useRouter(); const { messages, format } = useI18n(); const [status, setStatus] = useState(initialStatus); const [busy, setBusy] = useState<Action | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (["completed", "cancelled", "failed"].includes(status)) return; let stopped = false; let timer: number | undefined; const poll = async () => { try { const response = await fetch(`/api/campaigns/${campaignId}`, { cache: "no-store" }); const result = (await response.json()) as { status?: string }; if (!stopped && response.ok && result.status) setStatus(result.status); } finally { if (!stopped) timer = window.setTimeout(poll, 2_000); } }; timer = window.setTimeout(poll, 1_000); return () => { stopped = true; if (timer !== undefined) window.clearTimeout(timer); }; }, [campaignId, status]);
  const run = async (action: Action) => { if (action === "cancel" && !window.confirm(messages.ui.confirmCancelCampaign)) return; setBusy(action); setMessage(null); try { const response = await fetch(`/api/campaigns/${campaignId}/control`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const result = (await response.json()) as { status?: string; error?: string }; if (!response.ok || !result.status) throw new Error(result.error ?? format(messages.ui.controlFailed, { action })); setStatus(result.status); setMessage(action === "pause" ? messages.ui.pauseSuccess : action === "cancel" ? messages.ui.cancelSuccess : messages.ui.resumeSuccess); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : format(messages.ui.controlFailed, { action })); } finally { setBusy(null); } };
  const active = status === "sending"; const preparing = status === "dispatching"; const paused = status === "paused"; if (!active && !paused && !preparing) return null;
  return <section className="panel" style={{ marginBottom: 18 }}><div className="panelHeader"><div><p className="eyebrow">{messages.ui.campaignControls}</p><h2>{status}</h2><p className="subtitle">{preparing ? messages.ui.preparingControls : messages.ui.controlDescription}</p></div>{!preparing ? <div className="actionRow">{active ? <button className="secondary" disabled={busy !== null} onClick={() => void run("pause")} type="button">{busy === "pause" ? messages.ui.pausing : messages.ui.pause}</button> : null}{paused ? <button className="primary" disabled={busy !== null} onClick={() => void run("resume")} type="button">{busy === "resume" ? messages.ui.resuming : messages.ui.resume}</button> : null}<button className="secondary" disabled={busy !== null} onClick={() => void run("cancel")} type="button">{busy === "cancel" ? messages.ui.cancelling : messages.ui.cancelCampaign}</button></div> : null}</div>{message ? <p className="subtitle" style={{ marginTop: 12 }}>{message}</p> : null}</section>;
}
