"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/i18n-provider";
import { formatDateTimeLocalInZone, zonedLocalDateTimeToInstant } from "@/lib/campaign-scheduling";
import { campaignSchedulingMessages } from "@/lib/i18n/campaign-scheduling";
import { localeTag } from "@/lib/i18n";
type Action = "pause" | "resume" | "cancel" | "reschedule";

export function CampaignControls({ campaignId, initialStatus, initialScheduledAt, timeZone }: { campaignId: string; initialStatus: string; initialScheduledAt: string | null; timeZone: string }) {
  const router = useRouter(); const { messages, format, locale } = useI18n(); const scheduling = campaignSchedulingMessages[locale]; const scheduleDateTime = new Intl.DateTimeFormat(localeTag(locale), { dateStyle: "medium", timeStyle: "short", timeZone }); const [status, setStatus] = useState(initialStatus); const [scheduledAt, setScheduledAt] = useState(initialScheduledAt); const [scheduledLocal, setScheduledLocal] = useState(() => initialScheduledAt ? formatDateTimeLocalInZone(new Date(initialScheduledAt), timeZone) : ""); const [busy, setBusy] = useState<Action | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (["completed", "cancelled", "failed"].includes(status)) return; let stopped = false; let timer: number | undefined; const poll = async () => { try { const response = await fetch(`/api/campaigns/${campaignId}`, { cache: "no-store" }); const result = (await response.json()) as { status?: string; scheduledAt?: string | null }; if (!stopped && response.ok && result.status) { setStatus(result.status); if (result.scheduledAt !== undefined) { setScheduledAt(result.scheduledAt); if (result.scheduledAt) setScheduledLocal(formatDateTimeLocalInZone(new Date(result.scheduledAt), timeZone)); } } } finally { if (!stopped) timer = window.setTimeout(poll, 2_000); } }; timer = window.setTimeout(poll, 1_000); return () => { stopped = true; if (timer !== undefined) window.clearTimeout(timer); }; }, [campaignId, status, timeZone]);
  const run = async (action: Action) => { if (action === "cancel" && !window.confirm(messages.ui.confirmCancelCampaign)) return; setBusy(action); setMessage(null); try { const body: { action: Action; scheduledAt?: string } = { action }; if (action === "reschedule") { if (!scheduledLocal) throw new Error(scheduling.chooseScheduleTime); const instant = zonedLocalDateTimeToInstant(scheduledLocal, timeZone); if (instant.getTime() <= Date.now()) throw new Error(scheduling.futureScheduleRequired); body.scheduledAt = instant.toISOString(); } const response = await fetch(`/api/campaigns/${campaignId}/control`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = (await response.json()) as { status?: string; scheduledAt?: string; error?: string }; if (!response.ok || !result.status) throw new Error(result.error ?? format(messages.ui.controlFailed, { action })); setStatus(result.status); if (result.scheduledAt) { setScheduledAt(result.scheduledAt); setScheduledLocal(formatDateTimeLocalInZone(new Date(result.scheduledAt), timeZone)); } setMessage(action === "pause" ? messages.ui.pauseSuccess : action === "cancel" ? messages.ui.cancelSuccess : action === "resume" ? messages.ui.resumeSuccess : format(scheduling.campaignRescheduled, { timeZone })); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : format(messages.ui.controlFailed, { action })); } finally { setBusy(null); } };
  const active = status === "sending"; const preparing = status === "dispatching"; const paused = status === "paused"; const scheduled = status === "scheduled"; if (!active && !paused && !preparing && !scheduled) return null;
  const scheduleLabel = scheduledAt ? scheduleDateTime.format(new Date(scheduledAt)) : null;
  return <section className="panel" style={{ marginBottom: 18 }}><div className="panelHeader"><div><p className="eyebrow">{messages.ui.campaignControls}</p><h2>{status}</h2><p className="subtitle">{scheduled ? format(scheduling.scheduledDetail, { date: scheduleLabel ?? "—", timeZone }) : preparing ? messages.ui.preparingControls : messages.ui.controlDescription}</p></div>{!preparing && !scheduled ? <div className="actionRow">{active ? <button className="secondary" disabled={busy !== null} onClick={() => void run("pause")} type="button">{busy === "pause" ? messages.ui.pausing : messages.ui.pause}</button> : null}{paused ? <button className="primary" disabled={busy !== null} onClick={() => void run("resume")} type="button">{busy === "resume" ? messages.ui.resuming : messages.ui.resume}</button> : null}<button className="secondary" disabled={busy !== null} onClick={() => void run("cancel")} type="button">{busy === "cancel" ? messages.ui.cancelling : messages.ui.cancelCampaign}</button></div> : null}</div>{scheduled ? <div style={{ display: "grid", gap: 10, marginTop: 14 }}><label className="formLabel">{scheduling.scheduleTime}<input aria-label={scheduling.scheduleTime} type="datetime-local" value={scheduledLocal} onChange={(event) => setScheduledLocal(event.target.value)} /></label><div className="actionRow"><button className="primary" disabled={busy !== null || !scheduledLocal} onClick={() => void run("reschedule")} type="button">{busy === "reschedule" ? scheduling.rescheduling : scheduling.reschedule}</button><button className="secondary" disabled={busy !== null} onClick={() => void run("cancel")} type="button">{busy === "cancel" ? messages.ui.cancelling : messages.ui.cancelCampaign}</button></div></div> : null}{message ? <p className="subtitle" style={{ marginTop: 12 }}>{message}</p> : null}</section>;
}
