"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/i18n-provider";
type WabaOption = { wabaId: string; label: string };

export function TemplateManager({ wabas }: { wabas: WabaOption[] }) {
  const router = useRouter(); const { messages, number, format } = useI18n();
  const [wabaId, setWabaId] = useState(wabas[0]?.wabaId ?? ""); const [name, setName] = useState(""); const [language, setLanguage] = useState("en_US"); const [category, setCategory] = useState<"marketing" | "utility">("marketing"); const [body, setBody] = useState(""); const [footer, setFooter] = useState(""); const [examplesText, setExamplesText] = useState(""); const [busy, setBusy] = useState<"sync" | "create" | null>(null); const [message, setMessage] = useState<string | null>(null);
  const variableCount = useMemo(() => new Set([...body.matchAll(/\{\{(\d+)\}\}/g)].map((match) => Number(match[1]))).size, [body]);
  const syncTemplates = async () => { setBusy("sync"); setMessage(null); try { const response = await fetch("/api/templates/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(wabaId ? { wabaId } : {}) }); const result = (await response.json()) as { synced?: number; error?: string }; if (!response.ok) throw new Error(result.error ?? messages.ui.templateSyncFailed); setMessage(format(messages.ui.templatesSynced, { count: number(result.synced ?? 0) })); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : messages.ui.templateSyncFailed); } finally { setBusy(null); } };
  const createTemplate = async () => { setBusy("create"); setMessage(null); const examples = examplesText.split("\n").map((value) => value.trim()).filter(Boolean); try { const response = await fetch("/api/templates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ wabaId, name, language, category, body, footer: footer || undefined, examples }) }); const result = (await response.json()) as { status?: string; error?: string }; if (!response.ok) throw new Error(result.error ?? messages.ui.templateCreationFailed); setMessage(format(messages.ui.templateSubmitted, { status: result.status ?? "PENDING" })); setName(""); setBody(""); setFooter(""); setExamplesText(""); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : messages.ui.templateCreationFailed); } finally { setBusy(null); } };
  if (!wabas.length) return <p className="subtitle">{messages.ui.connectWabaFirst}</p>;
  return <div style={{ display: "grid", gap: 20 }}><div className="actionRow"><label className="formLabel" style={{ minWidth: 280, flex: "1 1 280px" }}>{messages.ui.waba}<select value={wabaId} onChange={(event) => setWabaId(event.target.value)}>{wabas.map((waba) => <option key={waba.wabaId} value={waba.wabaId}>{waba.label}</option>)}</select></label><button className="secondary" disabled={busy !== null} onClick={syncTemplates} type="button">{busy === "sync" ? messages.ui.syncing : messages.ui.syncFromMeta}</button></div><div style={{ borderTop: "1px solid var(--line)", paddingTop: 20, display: "grid", gap: 14 }}><div><p className="eyebrow">{messages.ui.createTemplate}</p><h2>{messages.ui.submitTextTemplate}</h2><p className="subtitle">{messages.ui.variableHint}</p></div><div className="formGrid3"><label className="formLabel">{messages.ui.templateName}<input value={name} onChange={(event) => setName(event.target.value.toLowerCase().replace(/[^a-z0-9_]+/g, "_"))} placeholder="september_offer" /></label><label className="formLabel">{messages.ui.languageLabel}<input value={language} onChange={(event) => setLanguage(event.target.value)} placeholder="en_US" /></label><label className="formLabel">{messages.ui.category}<select value={category} onChange={(event) => setCategory(event.target.value as "marketing" | "utility")}><option value="marketing">{messages.ui.marketing}</option><option value="utility">{messages.ui.utility}</option></select></label></div><label className="formLabel">{messages.ui.body} · {body.length}/1024<textarea rows={6} maxLength={1024} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Hi {{1}}, our September offer is ready for you." /></label><div className="formGrid2"><label className="formLabel">{messages.ui.footerOptional}<input maxLength={60} value={footer} onChange={(event) => setFooter(event.target.value)} placeholder={messages.ui.footerPlaceholder} /></label><label className="formLabel">{messages.ui.exampleValues} {variableCount ? format(messages.ui.examplesRequired, { count: number(variableCount) }) : ""}<textarea rows={3} value={examplesText} onChange={(event) => setExamplesText(event.target.value)} placeholder={variableCount ? "Yasser\n20% off" : messages.ui.noExamplesNeeded} /></label></div><div className="actionRow"><button className="primary" disabled={busy !== null || !wabaId || !name || !body} onClick={createTemplate} type="button">{busy === "create" ? messages.ui.submitting : messages.ui.submitToMeta}</button>{message ? <span className="subtitle">{message}</span> : null}</div></div></div>;
}
